# Generated by Django 3.0.5 on 2020-07-24 15:35

from django.db import migrations, models
import django.db.models.deletion
import petcare.models


class Migration(migrations.Migration):

    dependencies = [
        ("petcare", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "avatar",
                    models.FileField(
                        default="default.jpg",
                        upload_to=petcare.models.custom_media_path,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("specialist", models.CharField(blank=True, max_length=100, null=True)),
                ("data", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default="", max_length=100)),
                ("password", models.CharField(default="", max_length=32)),
                (
                    "avatar",
                    models.FileField(
                        default="default.jpg",
                        upload_to=petcare.models.custom_media_path,
                    ),
                ),
                ("gender", models.CharField(blank=True, max_length=15, null=True)),
                ("fullname", models.CharField(blank=True, max_length=1024, null=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "dateOfBirth",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.RemoveField(model_name="order", name="averageRating",),
        migrations.RemoveField(model_name="order", name="categories",),
        migrations.RemoveField(model_name="review", name="productImage",),
        migrations.RemoveField(model_name="review", name="productName",),
        migrations.RemoveField(model_name="review", name="productPrice",),
        migrations.RemoveField(model_name="review", name="productType",),
        migrations.RemoveField(model_name="shop", name="name",),
        migrations.RemoveField(model_name="shop", name="phoneNumber",),
        migrations.RemoveField(model_name="shop", name="userId",),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shopId",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="petcare.Shop",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="shopId",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="petcare.Shop",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="shopId",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="petcare.Shop",
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="avatar",
            field=models.FileField(
                default="default.jpg", upload_to=petcare.models.custom_media_path
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="password",
            field=models.CharField(default="", max_length=32),
        ),
        migrations.AddField(
            model_name="shop",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="ratings",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="username",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="productId",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="petcare.Product",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="shopId",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="petcare.Shop",
            ),
        ),
        migrations.AlterField(
            model_name="review", name="rating", field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="shop",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="email",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "shopId",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="petcare.Shop",
                    ),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="petcare.Customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("price", models.FloatField()),
                ("quantity", models.IntegerField(default=1)),
                (
                    "userId",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="petcare.Customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default="", max_length=100)),
                ("password", models.CharField(default="", max_length=32)),
                (
                    "avatar",
                    models.FileField(
                        default="default.jpg",
                        upload_to=petcare.models.custom_media_path,
                    ),
                ),
                ("gender", models.CharField(blank=True, max_length=15, null=True)),
                ("fullname", models.CharField(blank=True, max_length=1024, null=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "dateOfBirth",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("role", models.IntegerField(default=1)),
                ("customers", models.ManyToManyField(to="petcare.Customer")),
                ("products", models.ManyToManyField(to="petcare.Product")),
                ("shops", models.ManyToManyField(to="petcare.Shop")),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="carts",
            field=models.ManyToManyField(to="petcare.Cart"),
        ),
        migrations.AddField(
            model_name="review",
            name="userId",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="petcare.Customer",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="userId",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="petcare.Customer",
            ),
        ),
    ]
