# Generated by Django 3.0.5 on 2020-07-24 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0006_shop_warehouseaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='carts',
        ),
        migrations.AddField(
            model_name='cart',
            name='productId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='petcare.Product'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='username',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
