# Generated by Django 3.0.5 on 2020-07-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0007_auto_20200724_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='petcareuser',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petcareuser',
            name='isCustomer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petcareuser',
            name='isShop',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shop',
            name='businessLicense',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
