# Generated by Django 3.0.5 on 2020-07-25 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0011_auto_20200725_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('sender', models.SmallIntegerField(choices=[(1, 'CUSTOMER'), (2, 'SHOP')], default=1)),
                ('senderId', models.IntegerField(default=0)),
                ('content', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='chat',
            name='content',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='isVip',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='vipExpires',
        ),
        migrations.AddField(
            model_name='chat',
            name='messages',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='petcare.Message'),
        ),
    ]
